---
title: "Shift Work Case Study"
output: html_notebook
---



#**================================================================**
#** Libraries and Environment Setup                  **
#**================================================================**
```{r}
#** Load necessary libraries *
# Using pacman to install and load packages in one step
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  # Original Libraries
  dplyr,          # For data manipulation
  tidyr,          # For data tidying
  openxlsx,       # For reading/writing Excel files
  lubridate,      # For easier date-time manipulation
  data.table,     # For efficient data handling, especially rleid
  pracma,         # For findpeaks
  GLMMcosinor,    # For generalized linear mixed cosinor models
  circacompare,   # For comparing circadian rhythms
  tidyverse,      # A collection of R packages for data science
  brms,           # For Bayesian regression models using Stan
  rstanarm,       # For Bayesian models via RStan
  paletteer,      # Provides a collection of color palettes
  ggcorrplot,     # For visualizing correlation matrices
  ggpubr,         # For publication-ready plots
  corrr,          # For exploring correlations
  qgraph,         # For network analysis and visualization
  combinat,       # For combinatorics
  zoo,            # For ordered time series data
  caret,          # For classification and regression training
  janitor,        # For simple data cleaning
  pwr,            # For power analysis
  lmPerm,         # For permutation tests for linear models
  mgcv,            # For permutation tests for GAM
  pwr,
  rstatix,
  hms,
  fs,
  car
  
)

#** --- Set up a valid path --- *
# Define base paths for both possible directories
base_paths <- c(
  "E:/OneDrive/TUNCOM/TUNCRG/06. Phase 2 Data/Aging",
  "C:/Users/samue/OneDrive/TUNCOM/TUNCRG/06. Phase 2 Data/Aging"
)

# Find the first existing directory
valid_path <- first(base_paths[dir.exists(base_paths)])

if (is.na(valid_path)) {
  stop("Neither of the specified base directories exists. Please check the paths.")
}

#** --- Define objects to keep --- *
# This list helps in managing the global environment
CoreDatasets <- c(
"CorsanoAnalysismulti", "CorsanoAnalysissingle", "CorsanoAnalysisSleepexpand", "SleepAnalysis", "StatS", "CoreDatasets", "subjects", "SplitModel2", "Statistics", "biomarkers", "SleepStat", "Analysis", "CorsanoAnalysissplit", "valid_path", "processed_subjects", "Stat", "processed_subjects1", "processed_subjects2", "processed_subjects3", "CorsanoAnalysisAll", "Shiftwork", "Shiftwork2", "ShiftStat", "Sleepwork", "CorsanoAnalysisSleepmulti", "CorsanoAnalysisSleepsingle", "CorsanoAnalysisWave", "PhaseDiff", "SLEEP", "CorsanoShiftWave", "Variability", "Stability", "SJL", "StatSS", "SLEEP1", "AmpMesAge", "AmpMesGen", "BioBmiStats", "DeviationsS", "SJLDeviations", "SJLBIO", "jsl_summary", "Jetlag", "biolist", "PhysCog", "Aging", "AgingA", "SJL2", "SJLBio"
)


# Biolist
biolist <- c("HR", "Steps", "Energy", "Breath", "HRV", "RR", "Cortisol", "Stress", "SBT", "CBT")

# Clean up
rm(list = setdiff(ls(), CoreDatasets))
```



#** Set up Dataframe
```{r}
# Create Shiftwork Dataframe
Shiftwork <- CorsanoAnalysismulti %>%
  filter(Subject == "TX39EXWDv2") %>%
  mutate(Time = Time/24,
         Time = 11 + Time) %>%
  mutate(Treat = ifelse(Time < 18, "PreTreatment", "Treatment1")) %>%
  group_by(Subject, Treat, Time) %>%
  mutate(Time = Time - 11,
         Time = Time * 24,
         Time = Time %% 24)

Shiftworktmp <- CorsanoAnalysismulti %>%
  filter(Subject == "TX39EXWDv3") %>%
  mutate(Treat = "Treatment2",
         Time = Time %% 24) %>%
  group_by(Subject, Treat, Time)


Shiftwork <- rbind(Shiftwork, Shiftworktmp)

 


# Duplicate rows where Time == 0, change Time to 24, and add them back
Shiftwork2 <- Shiftwork %>%
  filter( Time < 360) %>%
  bind_rows(Shiftwork %>%
      filter(Time == 0) %>%
      mutate(Time = 24)) %>%
  mutate(Subject = "TX39EXWD") %>%
  mutate(Time = round(Time, 1)) %>%
  arrange(Subject, Treat, Time) %>%
  select(-Day)






# Create a dataset where it's already combined to a single day
Shiftwork3 <- Shiftwork2 %>%
  group_by(Time, Subject, Treat) %>%
  summarise(
    HRSEM = sd(HR, na.rm = TRUE) / sqrt(sum(!is.na(HR))),
    HR = mean(HR, na.rm = TRUE),
    
    StepsSEM = sd(Steps, na.rm = TRUE) / sqrt(sum(!is.na(Steps))),
    Steps = mean(Steps, na.rm = TRUE),
    
    EnergySEM = sd(Energy[Energy != 0], na.rm = TRUE) / sqrt(sum(!is.na(Energy[Energy != 0]))),
    Energy = mean(Energy[Energy != 0], na.rm = TRUE),
    
    BreathSEM = sd(Breath, na.rm = TRUE) / sqrt(sum(!is.na(Breath))),
    Breath = mean(Breath, na.rm = TRUE),
    
    HRVSEM = sd(HRV, na.rm = TRUE) / sqrt(sum(!is.na(HRV))),
    HRV = mean(HRV, na.rm = TRUE),
    
    RRSEM = sd(RR, na.rm = TRUE) / sqrt(sum(!is.na(RR))),
    RR = mean(RR, na.rm = TRUE),
    
    CortisolSEM = sd(Cortisol, na.rm = TRUE) / sqrt(sum(!is.na(Cortisol))),
    Cortisol = mean(Cortisol, na.rm = TRUE),
    
    StressSEM = sd(Stress, na.rm = TRUE) / sqrt(sum(!is.na(Stress))),
    Stress = mean(Stress, na.rm = TRUE),
    
    SBTSEM = sd(SBT, na.rm = TRUE) / sqrt(sum(!is.na(SBT))),
    SBT = mean(SBT, na.rm = TRUE),
    
    CBTSEM = sd(CBT, na.rm = TRUE) / sqrt(sum(!is.na(CBT))),
    CBT = mean(CBT, na.rm = TRUE)
    ) %>%
  ungroup() %>%
  arrange(Subject, Treat, Time)
  

```



#** Comparison between Pre and Post treatment
```{r}
Shiftwork6 <- Shiftwork %>%
  filter(Treat != "Treatment1")

# Running cglmm
ShiftworkModel <- cglmm(
  CBT ~ 0 + Treat + amp_acro(
    time_col = 'Time',
    n_components = 2,
    period = c(24, 12),
    group = Treat),
    data = Shiftwork6
)


ShiftworkModel
autoplot(ShiftworkModel, superimpose.data = FALSE)

```



#** generate graphs for shift work pre and post treatment
```{r}
# Define the Loop lists
subjectnames <- unique(Shiftwork2$Subject)
weekz <- unique(Shiftwork2$Treat)
biolist <- c("HR", "Steps", "Energy", "Breath", "HRV", "RR", "Cortisol", "Stress", "SBT", "CBT")


# WaveData
  CorsanoShiftWave <- data.frame()


# Function to replace NULL and NaN with NA
  replace_nan_with_NA <- function(x) {
    if(is.null(x)) {
    return(NA)
    } else {
      x[is.nan(x)] <- NA
      return(x)
      }
  }



# Loop through each subject
for (subject in subjectnames) {
    cat("Processing Patient:", subject, "\n")
  
  
    # Create a folder for the current subject (if it doesn't already exist)
    subject_folder <- paste0(valid_path, "/Shift Work/", subject)
    if (!dir.exists(subject_folder)) {
        dir.create(subject_folder, recursive = TRUE)
        cat("Created folder for patient:", subject, "\n")
    }
  
  # Loop through weekdays and weekends
  for (dayz in weekz) {
    cat("Processing Day:", dayz, "\n")
    
    # Initialize empty data frame for Wavedatatmp
      Wavedatatmp <- data.frame()
    
    # Loop through metrics
    for (bio in biolist) {
      cat("Processing biometric:", bio, "\n")
      
  
      # Filter data for the current subject
      GLMMSplit <- Shiftwork2 %>%
        filter(Subject == subject,
               Treat == dayz)
      
      #** Skip if GLMMSplit has less than 70 rows **
      if (nrow(GLMMSplit) < 70)  {
      next
      } 

      # Run GLMM Cosinor Analysis
      SplitModel2 <- cglmm(as.formula(paste(
        bio, "~ amp_acro(
        time_col = 'Time', 
        period = c(24, 12), 
        n_components = 2)")),
      data = GLMMSplit)
     
      # Create Graphable data
      prediction <- predict(SplitModel2, GLMMSplit)
      Wavedatatmp1 <- GLMMSplit[, c("Time", bio)]
      Wavedatatmp1[[paste0(bio, "Cosine")]] <- prediction
      
      Wavedatatmp1 <- Wavedatatmp1 %>%
        group_by(Time) %>%
        summarise(
                  !!paste0(bio, "SEM") := sd(!!sym(bio), na.rm = TRUE) / sqrt(sum(!is.na(!!sym(bio)))),
                  !!paste0(bio) := mean(!!sym(bio), na.rm = TRUE),
                  !!paste0(bio, "Cosine") := mean(!!sym(paste0(bio, "Cosine")))
                  )
      
      # Join this biomarker's results to the cumulative data frame (Wavedatatmp)
            if (nrow(Wavedatatmp) == 0) {
                Wavedatatmp <- Wavedatatmp1  # If it's the first biomarker, directly assign
            } else {
                Wavedatatmp <- left_join(Wavedatatmp, Wavedatatmp1, by = "Time")  # Add new columns for subsequent biomarkers
            }
      
      
        } # End of loop for each metric
      
      
      #** Skip if GLMMSplit has less than 70 rows *
      if (nrow(GLMMSplit) > 70)  {

        # Create Double graph
        Wavedatatmp2 <- Wavedatatmp %>%
          mutate(Time = Time + 24) %>%
          filter(Time != 24)
        
        Wavedata <- bind_rows(Wavedatatmp, Wavedatatmp2)
        Wavedata <- Wavedata %>%
          select(Time, CBT, CBTCosine, CBTSEM, HR, HRCosine, HRSEM, 
                 Breath, BreathCosine, BreathSEM, HRV, HRVCosine, 
                 HRVSEM, RR, RRCosine, RRSEM, Cortisol,CortisolCosine, 
                 CortisolSEM, Stress, StressCosine, StressSEM, SBT, SBTCosine, 
                 SBTSEM, Steps, StepsCosine, StepsSEM, Energy,EnergyCosine, EnergySEM)
      
        # Replace all NaN with NA
        Wavedata <- as.data.frame(lapply(Wavedata, replace_nan_with_NA))
          
          
          
       #** Export the data *
          export_path <- paste0(subject_folder, "/", subject, " ", dayz, " Wave", ".xlsx")
          write.xlsx(Wavedata, export_path, rowNames = FALSE, firstRow = TRUE)
          
        #** Copy Data into Graphing Template **
        Template <- paste0(valid_path, "/Graphing Template.xlsx")
        Graph <- paste0(valid_path, "/Shift Work/", subject, "/", subject, " Diff.xlsx")
        Graph2 <- paste0(valid_path, "/Shift Work/", subject, "/", subject, " ", dayz, ".xlsx")
        
        #  if (!file.exists(Graph)) {
        #    file.copy(from = Template, to = Graph)
        #  }
        #
          # Check if the file was copied successfully
        #    if (file.exists(Graph)) {
        #      cat("File copied and renamed successfully to:", subject,"\n")
        #    } else {
        #      cat("Failed to copy and rename the file.\n")
        #    }
        
        
        #** Making Edits to Graph **
        # Load the workbook into R
        wb <- loadWorkbook(Graph)
        wb2 <- loadWorkbook(Graph2)
        
        # Load data into appropriate sheet
        writeData(wb, sheet = dayz, x = Wavedata)
        writeData(wb2, sheet = dayz, x = Wavedata)
        
        # Save modified workbook
        saveWorkbook(wb, Graph, overwrite = TRUE)
        cat("Graph for", subject," Diff successfully made and saved\n")
        
        saveWorkbook(wb2, Graph2, overwrite = TRUE)
        cat("Graph for", subject, " ", dayz, " successfully made and saved\n")
        
        
        
      #** Save the Wave Data **
        Wavedatatmp3 <- Wavedata %>%
        select(Time, CBTCosine, HRCosine, BreathCosine, HRVCosine, RRCosine, CortisolCosine, StressCosine, SBTCosine, StepsCosine, EnergyCosine) %>%
        mutate(Treat = dayz)
        
        CorsanoShiftWave <- rbind(CorsanoShiftWave, Wavedatatmp3)  
        
        
        
      } else {
        cat("Skipping due to insufficient data\n")
        next
        } 

      # Clear out Wavedatatmp for next loop  
        rm(Wavedatatmp)

    } # End of Weekday vs Weekend
    # Add subject to processed list after it's complete
  } # End of entire loop
  

# Clean up
rm(list = setdiff(ls(), CoreDatasets))
```




#** Analyze Sleep data pre and post treatment
```{r}
Sleepwork <- SleepStatRaw %>%
  filter(Subject == "TX39EXWDv2") %>%
  mutate(SleepPeriod = SleepPeriod + 10) %>%
  mutate(Treat = ifelse(SleepPeriod < 18, "PreTreatment", "PostTreatment")) %>%
  filter(SleepPeriod < 26) %>%
  select(-SleepPeriod) %>%
  group_by(Subject, Treat) %>%
  summarise(
            SLP = mean(SLP) / 60,
            `Deep%` = mean(`Deep%`),
            Deep = mean(Deep),
            `Light%` = mean(`Light%`),
            Light = mean(Light),
            `NREM%` = mean(`NREM%`),
            NREM = mean(NREM),
            `REM%` = mean(`REM%`),
            REM = mean(REM),
            `Awake%` = mean(`Awake%`),
            Wake = mean(Wake)
            )
  

```




#* Statistical Analysis Output for shiftwork
```{r}
# Define the Loop lists
weekz <- unique(CorsanoShiftWave$Treat)
biolist <- c("HR", "Steps", "Energy", "Breath", "HRV", "RR", "Cortisol", "Stress", "SBT", "CBT")


if (file.exists(paste0(valid_path, "/Documentations/patients.xlsx"))) {
  PT <- read.xlsx(paste0(valid_path, "/Documentations/patients.xlsx"))
} 

# Function to replace NULL and NaN with NA
  replace_nan_with_NA <- function(x) {
    if(is.null(x)) {
    return(NA)
    } else {
      x[is.nan(x)] <- NA
      return(x)
      }
  }

# Check to see if Stat has been created yet
if (!is.data.frame(Stat)) {
  ShiftStat <- data.frame()
}
#Stat <- data.frame() # Use this if resetting Stat
  
# Initialize empty data frame for stattmp
  Stattmp <- data.frame()
  

  # Loop through Treatments
  for (dayz in weekz) {
    cat("Processing Day:", dayz, "\n")
    
    # Filter data for the current subject
      GLMMSplit <- CorsanoShiftWave %>%
        filter(Treat == dayz) %>%
        rename(CBT = CBTCosine,
               HR = HRCosine,
               Breath = BreathCosine,
               HRV = HRVCosine,
               RR = RRCosine,
               Cortisol = CortisolCosine,
               Stress = StressCosine,
               SBT = SBTCosine,
               Steps = StepsCosine,
               Energy = EnergyCosine) %>%
        mutate(across(everything(), ~ replace_nan_with_NA(.)))
    
    # Loop through metrics
    for (bio in biolist) {
      cat("Processing biometric:", bio, "\n")
      

      #** Skip if GLMMSplit has less than 70 rows or if any column has more than 37 consecutive NAs **
      if (nrow(GLMMSplit) < 70 || any(rle(is.na(GLMMSplit[[bio]]))$lengths[which(rle(is.na(GLMMSplit[[bio]]))$values)] > 37)) {
        cat("Skipping due to insufficient data \n")
        next
      }
          
          # Calculate min and minTime
          min <- min(GLMMSplit[[bio]], na.rm = TRUE)
          minTime <- GLMMSplit$Time[which.min(GLMMSplit[[bio]])]
          
          # Calculate max and maxTime
          max <- max(GLMMSplit[[bio]], na.rm = TRUE)
          maxTime <- GLMMSplit$Time[which.max(GLMMSplit[[bio]])]
          
          # Calculate Amp
          amp <- (max - min)/2
          
          # Calculate MESOR
          mesor <- mean(GLMMSplit[[bio]], na.rm = TRUE)
          
          test_long <- data.frame(Bio = paste0(bio),
                                  Treat = dayz,
                                  Amplitude = amp,
                                  Max = max,
                                  Min = min,
                                  Mesor = mesor,
                                  PPhase = maxTime,
                                  TPhase = minTime)

      
      # Join this biomarker's results to the cumulative data frame (Wavedatatmp)
            if (nrow(Stattmp) == 0) {
                Stattmp <- test_long  # If it's the first biomarker, directly assign
            } else {
                Stattmp <- rbind(Stattmp, test_long)
            }
      
          } # End of loop for each metric
      } # End of entire loop


ShiftStat <- Stattmp
  
  
# Attach Sleep Stats with Stat
#ShiftStat <- ShiftStat %>%
#  left_join(Sleepwork, by = c("Treat" = "Treat"))


#** Export the data *
  export_path <- paste0(valid_path, "/Stats/Shift Work Statistics NEW.xlsx")
  write.xlsx(ShiftStat, export_path, rowNames = FALSE, firstRow = TRUE)
  
        

# Clean up
rm(list = setdiff(ls(), CoreDatasets))
```




#** Comparison between Pre and Post treatment statistics
```{r}
ShiftworkA <- Shiftwork %>%
  filter(Treat == "PreTreatment")

ShiftworkB <- Shiftwork %>%
  filter(Treat == "Treatment1")


ShiftworkC <- Shiftwork %>%
  filter(Treat == "Treatment2")


preT <- cglmm(
  CBT ~ amp_acro(
    time_col = Time,
    n_components = 2,
    period = c(24, 12)),
    data = ShiftworkA
)

T1 <- cglmm(
  CBT ~ amp_acro(
    time_col = Time,
    n_components = 2,
    period = c(24, 12)),
    data = ShiftworkB
)

T2 <- cglmm(
  CBT ~ amp_acro(
    time_col = Time,
    n_components = 2,
    period = c(24, 12)),
    data = ShiftworkC
)



preT
autoplot(preT, superimpose.data = FALSE)

T1
autoplot(T1, superimpose.data = FALSE)

T2
autoplot(T2, superimpose.data = FALSE)


anova(preT$fit, T1$fit)

```


```{r}
ShiftworkA <- Shiftwork %>%
  filter(Treat != "PreTreatment")

ShiftworkB <- Shiftwork %>%
  filter(Treat != "Treatment1")


ShiftworkC <- Shiftwork %>%
  filter(Treat != "Treatment2")



results <- circacompare(
  x = ShiftworkB,
  col_time = "Time",
  col_group = "Treat",
  col_outcome = "CBT",
  period = 24
)

results1 <- circacompare(
  x = ShiftworkC,
  col_time = "Time",
  col_group = "Treat",
  col_outcome = "CBT",
  period = 24
)

results2 <- circacompare(
  x = ShiftworkA,
  col_time = "Time",
  col_group = "Treat",
  col_outcome = "CBT",
  period = 24
)

results
results1
results2
```



